logging:
  level:
    #    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace
    org.springframework.security: trace
spring:
  datasource:
    # Database connection URL
    url: ${SPRING_DATASOURCE_URL}
    # Database username
    username: ${SPRING_DATASOURCE_USERNAME}
    # Database password
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        # The SQL dialect to use for the database
        dialect: org.hibernate.dialect.MySQL8Dialect
#Client:
client:
  origin: ${CLIENT_ORIGIN}