logging:
  level:
    #    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
#    org.hibernate.orm.jdbc.extract: trace
    org.hibernate.orm.jdbc.extract: info
#    org.springframework.security: trace
    org.springframework.security: info
spring:
  datasource:
    # Database connection URL
    url: jdbc:mysql://localhost:50000/bocchi_the_twitter?allowPublicKeyRetrieval=true&useSSL=false&connectionTimeZone=SERVER&useLegacyDatetimeCode=false
    # Database username
    username: root
    # Database password
    password: password
  jpa:
    properties:
      hibernate:
        # The SQL dialect to use for the database
        dialect: org.hibernate.dialect.MySQL8Dialect
client:
  origin: "http://localhost:8081"
